from django.urls import path
from smartdns import views

urlpatterns = [
    path('cluster/', views.cluster, name = 'cluster'),
    path('cluster/add/', views.cluster_add, name = 'cluster_add'),
    path('cluster/delete/<int:cluster_id>/', views.cluster_del, name = 'cluster_del'),
    path('cluster/edit/<int:cluster_id>/', views.cluster_mod, name = 'cluster_mod'),
    path('server/', views.server, name = 'server'),
    path('server/add/', views.add_server, name = 'add_server'),
    path('server/delete/<int:server_id>/', views.delete_server, name = 'delete_server'),
    path('server/edit/<int:server_id>/', views.edit_server, name = 'edit_server'),
    path('view/', views.view, name = 'view'),
    path('view/add/', views.add_view, name = 'add_view'),
    path('view/key/<int:view_id>/', views.view_key, name = 'view_key'),
    path('view/edit/<int:view_id>/', views.edit_view, name = 'edit_view'),
    path('view/delete/<int:view_id>/', views.delete_view, name = 'delete_view'),
    path('zone/', views.zone, name = 'zone'),
    path('zone/add/', views.add_zone, name = 'add_zone'),
    path('zone/edit/<int:zone_id>/', views.edit_zone, name = 'edit_zone'),
    path('zone/delete/<int:zone_id>/', views.delete_zone, name = 'delete_zone'),
    path('record/', views.record, name = 'record'),
    path('record/detail/<int:zone_id>/<int:view_id>/', views.record_detail, name = 'record_detail'),
    path('record/add/', views.add_record_null, name = 'add_record_null'),
    path('record/add/<int:zone_id>/<int:view_id>/', views.add_record, name = 'add_record'),
    path('record/edit/<int:zone_id>/<int:view_id>/<int:record_id>/', views.edit_record, name = 'edit_record'),
    path('record/delete/<int:zone_id>/<int:view_id>/<int:record_id>/', views.delete_record, name = 'delete_record'),
    path('record/note/<int:zone_id>/<int:view_id>/<int:record_id>/', views.record_note, name = 'record_note'),
    path('record/input/<int:zone_id>/<int:view_id>/', views.input_record, name = 'input_record'),
    path('record/output/<int:zone_id>/<int:view_id>/', views.output_record, name = 'output_record'),
    path('audit/', views.audit, name = 'audit'),
    path('help/', views.help, name = 'help'),
    path('display_meta/', views.display_meta),
]
