# Generated by Django 2.2 on 2019-11-04 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='保存日期')),
            ],
            options={
                'db_table': 'smartdns_audit',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('cremark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'smartdns_cluster',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('acl', models.TextField(max_length=1000, verbose_name='ACL')),
                ('vremark', models.CharField(max_length=50, verbose_name='描述')),
                ('secret', models.CharField(blank=True, max_length=50, null=True, verbose_name='KEY')),
            ],
            options={
                'db_table': 'smartdns_view',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zname', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('zremark', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'db_table': 'smartdns_zone',
            },
        ),
        migrations.CreateModel(
            name='zone_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.View')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdns.Zone')),
            ],
            options={
                'db_table': 'smartdns_zone_view',
            },
        ),
        migrations.AddField(
            model_name='zone',
            name='view',
            field=models.ManyToManyField(through='smartdns.zone_view', to='smartdns.View'),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(choices=[('master', 'Master'), ('slave', 'Slave')], default='Slave', max_length=20, verbose_name='服务器')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('sremark', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.Cluster')),
            ],
            options={
                'db_table': 'smartdns_server',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=50, verbose_name='主机记录')),
                ('rdtype', models.CharField(choices=[('A', 'A'), ('CNAME', 'CNAME'), ('NS', 'NS')], default='A', max_length=5, verbose_name='记录类型')),
                ('rdata', models.CharField(max_length=50, verbose_name='记录值')),
                ('ttl', models.IntegerField(default='600', verbose_name='TTL(s)')),
                ('rremark', models.CharField(max_length=50, verbose_name='备注')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.View')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.Zone')),
            ],
            options={
                'db_table': 'smartdns_record',
            },
        ),
    ]
