# Generated by Django 2.2 on 2019-11-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='view',
            field=models.ManyToManyField(blank=True, null=True, through='smartdns.zone_view', to='smartdns.View'),
        ),
        migrations.AlterField(
            model_name='zone_view',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.Zone'),
        ),
    ]
