# Generated by Django 2.2 on 2019-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdns', '0002_auto_20191106_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='secret',
            field=models.CharField(max_length=50, verbose_name='KEY'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='view',
            field=models.ManyToManyField(blank=True, through='smartdns.zone_view', to='smartdns.View'),
        ),
    ]
