# Generated by Django 2.2 on 2020-06-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdns', '0003_auto_20191106_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rremark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='record',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.View', verbose_name='视图'),
        ),
        migrations.AlterField(
            model_name='record',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smartdns.Zone', verbose_name='域'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sname',
            field=models.CharField(choices=[('master', '权威'), ('slave', '边缘'), ('cache', '缓存')], default='权威', max_length=20, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='zone_view',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdns.View'),
        ),
        migrations.AlterField(
            model_name='zone_view',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdns.Zone'),
        ),
    ]
