# Generated by Django 2.2 on 2020-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdns', '0004_auto_20200616_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rremark',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
    ]
