# Generated by Django 2.2 on 2020-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdns', '0005_auto_20200618_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cremark',
            field=models.CharField(blank=True, max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sremark',
            field=models.CharField(blank=True, max_length=20, verbose_name='备注'),
        ),
    ]
